# Generated by Django 2.2.16 on 2021-08-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_comment_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',)},
        ),
    ]
