# Generated by Django 2.2.16 on 2021-08-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20210811_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='descrpition',
            new_name='descrption',
        ),
    ]
