# Generated by Django 2.2.16 on 2021-08-20 20:07

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20210817_1515'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_title_author',
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, validators=[reviews.models.no_future_date], verbose_name='review_pub_date'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_title_author'),
        ),
    ]
